name: Run tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Run tests
        with:
          SUPABASE_KEY: ${{ secrets.SUPABSE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABSE_URL }}
        env:
          SUPABASE_KEY: ${{ secrets.SUPABSE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABSE_URL }}
        run: bun install && bun test
