name: Run tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Run tests
        env:
          SB_KEY: ${{ secrets.SUPABSE_KEY }}
          SB_URL: ${{ secrets.SUPABSE_URL }}
        run: SUPABASE_KEY=SB_KEY SUPABASE_URL=SB_URL bun install && bun test
